"""
AgriSustain AI — Responsible AI Validation Layer
Checks AI-generated responses before delivery to the user.

Validation dimensions:
  1. Safety          — detects potentially dangerous chemical/pesticide instructions
  2. Uncertainty     — prevents presenting uncertain predictions as guaranteed facts
  3. False Caps      — prevents claiming live data or capabilities not available
  4. Privacy         — prevents requesting unnecessary personal information
  5. Groundedness    — warns when answer is not backed by retrieved knowledge

This module does NOT modify the AI response content — it annotates it with
flags and warnings that are displayed to the user as transparency information.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import List, Optional


# ──────────────────────────────────────────────────────────────────────────────
# DATA MODELS
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class ValidationFlag:
    dimension: str       # Which Responsible AI dimension triggered
    severity: str        # "warning" | "info"
    message: str         # Human-readable explanation


@dataclass
class ValidationResult:
    passed: bool                              # True if no warnings were raised
    flags: List[ValidationFlag] = field(default_factory=list)
    transparency_note: Optional[str] = None  # Final note appended to the response


# ──────────────────────────────────────────────────────────────────────────────
# PATTERN LIBRARIES
# ──────────────────────────────────────────────────────────────────────────────

# Phrases that suggest a fabricated or dangerous chemical dosage/instruction
_SAFETY_PATTERNS = [
    r"\b(\d+\s?(ml|litre|liter|gram|kg|g/l|ppm)\s?(per|of|per\s?litre))",  # dosage numbers
    r"\bapply\s+\d+",          # "apply 5 ml"
    r"\bspray\s+\d+",          # "spray 200 ml"
    r"\bmix\s+\d+",            # "mix 10 g"
    r"\b(chlorpyrifos|endosulfan|monocrotophos|methyl parathion|dichlorvos)\b",  # banned/dangerous
]

# Phrases that present uncertain outcomes as guaranteed
_CERTAINTY_PATTERNS = [
    r"\b(will definitely|guaranteed to|100%|certainly produce|exact yield|will produce \d+)\b",
    r"\byour (farm|crop|field) will (produce|yield|give|get) [\d,]+\b",
    r"\bpredicted yield (is|will be) [\d,]+\b",
]

# Phrases falsely claiming live/real-time data
_FALSE_CAPS_PATTERNS = [
    r"\b(i checked|checked today.?s weather|current weather (is|shows))\b",
    r"\baccording to (the government|official|live|real.?time)\b",
    r"\bthe (database|api|live) (shows|says|confirms)\b",
    r"\bi analyzed (the image|your image|this image)\b",
    r"\bcrop price (today|currently|right now) (is|are)\b",
]

# Phrases requesting unnecessary personal data
_PRIVACY_PATTERNS = [
    r"\b(aadhaar|aadhar|pan card|social security|ssn|passport number)\b",
    r"\b(bank account|account number|credit card|debit card)\b",
    r"\b(password|pin|otp|one.?time password)\b",
    r"\bgovernment id\b",
]


def _check_patterns(text: str, patterns: List[str]) -> List[str]:
    """Return list of matched pattern strings found in text."""
    found = []
    t = text.lower()
    for p in patterns:
        if re.search(p, t):
            found.append(p)
    return found


# ──────────────────────────────────────────────────────────────────────────────
# VALIDATOR
# ──────────────────────────────────────────────────────────────────────────────

def validate_response(
    response_text: str,
    rag_was_used: bool,
    rag_retrieved: bool,
    query_requires_rag: bool = False,
) -> ValidationResult:
    """
    Validate an AI-generated response against Responsible AI principles.

    Args:
        response_text: The text generated by IBM Granite.
        rag_was_used: Whether the RAG retrieval tool was called for this response.
        rag_retrieved: Whether the RAG tool actually returned relevant documents.
        query_requires_rag: Whether this query type typically requires grounded knowledge.

    Returns:
        A ValidationResult with flags and an optional transparency note.
    """
    flags: List[ValidationFlag] = []

    # ── 1. Safety check ───────────────────────────────────────────────────────
    safety_hits = _check_patterns(response_text, _SAFETY_PATTERNS)
    if safety_hits:
        flags.append(ValidationFlag(
            dimension="Safety",
            severity="warning",
            message=(
                "This response may contain specific chemical dosage or pesticide "
                "instructions. These have not been verified against a product label "
                "or official source. Always follow the product label and consult "
                "a qualified agricultural extension officer before applying any "
                "chemical treatment."
            ),
        ))

    # ── 2. Uncertainty check ─────────────────────────────────────────────────
    certainty_hits = _check_patterns(response_text, _CERTAINTY_PATTERNS)
    if certainty_hits:
        flags.append(ValidationFlag(
            dimension="Uncertainty",
            severity="warning",
            message=(
                "This response may contain language that presents uncertain "
                "agricultural outcomes as guaranteed results. Crop yield, disease "
                "outcomes, and weather-dependent results cannot be guaranteed — "
                "they depend on many local factors including weather, soil, variety, "
                "and crop management."
            ),
        ))

    # ── 3. False capabilities check ──────────────────────────────────────────
    false_caps_hits = _check_patterns(response_text, _FALSE_CAPS_PATTERNS)
    if false_caps_hits:
        flags.append(ValidationFlag(
            dimension="Transparency",
            severity="warning",
            message=(
                "This response may claim access to live weather data, real-time "
                "crop prices, government databases, or image analysis capabilities "
                "that are not actually connected to this system. "
                "AgriSustain AI does not have access to live data in this session."
            ),
        ))

    # ── 4. Privacy check ─────────────────────────────────────────────────────
    privacy_hits = _check_patterns(response_text, _PRIVACY_PATTERNS)
    if privacy_hits:
        flags.append(ValidationFlag(
            dimension="Privacy",
            severity="warning",
            message=(
                "This response appears to request personal identification, financial, "
                "or authentication information. AgriSustain AI never needs this "
                "information. Do not share passwords, bank details, or government "
                "identification numbers."
            ),
        ))

    # ── 5. Groundedness check ────────────────────────────────────────────────
    if query_requires_rag and not rag_retrieved:
        flags.append(ValidationFlag(
            dimension="Groundedness",
            severity="info",
            message=(
                "The agricultural knowledge base did not return a matching document "
                "for this question. The answer below is based on general knowledge "
                "from the language model, not from a verified agricultural source. "
                "Treat it as general guidance only."
            ),
        ))

    # ── Build transparency note ───────────────────────────────────────────────
    passed = not any(f.severity == "warning" for f in flags)

    transparency_parts = []
    if rag_retrieved:
        transparency_parts.append(
            "📚 *This response includes information retrieved from the "
            "AgriSustain agricultural knowledge base.*"
        )
    else:
        transparency_parts.append(
            "💬 *This response is based on general agricultural knowledge "
            "from IBM Granite. No specific document was retrieved from the "
            "knowledge base for this query.*"
        )

    transparency_parts.append(
        "⚠️ *AgriSustain AI is a decision-support tool. Consult a local "
        "agricultural extension officer or agronomist for site-specific advice.*"
    )

    transparency_note = "\n\n---\n" + "\n\n".join(transparency_parts)

    return ValidationResult(
        passed=passed,
        flags=flags,
        transparency_note=transparency_note,
    )


def format_validation_warnings(result: ValidationResult) -> str:
    """
    Format any validation warnings as a visible block appended to the response.
    Only warning-level flags are shown to the user.
    """
    warnings = [f for f in result.flags if f.severity == "warning"]
    if not warnings:
        return ""

    lines = ["\n\n---\n### ⚠️ Responsible AI Notice"]
    for flag in warnings:
        lines.append(f"**{flag.dimension}:** {flag.message}")
    return "\n\n".join(lines)
